### ISSUE TITLE
af封装

### ISSUE THREAD

**Issue by cyqluowang** [lizelu/MVVM#1]
我想问下你这样封装AF的话，如果多个http并发的时候怎么处理？
QQ:573700261

**Comment by lizelu** [comment]
你可以这样做一个实验，在并发请求中打印一下封装方法中的局部变量的地址，看是否相同？如果在多线程下的话，可以在ViewMode中加上同步锁~再做这个工程的时候，只想了一些如何去分层，更为细节性的东西没有去考虑~抱歉~

**Comment by ziyuxu** [comment]
帅哥能否留下一个联系方式啊
