### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by jj89757hhb** [lizelu/MVVM#2]
就是这里封装了一下
PublicWeiboViewModel *publicViewModel = [[PublicWeiboViewModel alloc] init];
    [publicViewModel weiboDetailWithPublicModel:_publicModelArray[indexPath.row] WithViewController:self];
我感觉会很绕  mvvm真的牛逼吗   感觉不太习惯这么去写

**Comment by lizelu** [comment]
主要是想把业务逻辑提出来，便于维护，可以把业务逻辑，数据验证，页面跳转放到ViewModel层。而页面展示，页面效果放在VC和View中。不管是MVC, MVVM还是MVCS没有什么牛B不牛B的，只有合不合适。如果你有其他的架构，这种架构也许是你独有的，很适合你当前开发的工程，那么这个架构就牛B。有些人经常把MVVM与ReactiveCocoa联系在一起，感觉没有ReactiveCocoa的工程就不是MVVM, ReactiveCocoa固然强大，不过整个团队的学习成本还是要考虑的。如果你现在的工程，按原来的方式开发出来便于维护和迭代功能，那就没必要改变了~

**Comment by jj89757hhb** [comment]
有道理

**Comment by longhongwei17** [comment]
找到适合自己的 就好  我一般会把tableView 的一长串代理抽出去 要不VC 就很臃肿
