### ISSUE TITLE
有关MVVM

### ISSUE THREAD

**Issue by lizy0927** [lizelu/MVVM#3]
MVVM中VM 在你看来只是做了一次数据获取、转换、返回么？  感觉思想有点偏差 cell 不应持有model哦

**Comment by XXYYdY** [comment]
这个只是伪MVVM，只是MVC变个形而已。

**Comment by lizelu** [comment]
这只是个Demo而已，MVVM的实现还要根据具体业务来处理的，VM层本来就是从VC层剥离出来的，VM层所容纳的东西还要根据具体的业务逻辑进行处理，不可一概而论。该Demo主要是如何将M-VM-C进行解耦。其实没有必要往MVVM上靠拢，关键还是根据业务进行模块的拆分，便于后期扩充和维护~

**Comment by lizelu** [comment]
另外的可以看一下这一篇博客：http://www.cnblogs.com/ludashi/p/4925042.html

**Comment by rushairer** [comment]
Table view data source 应该放VM里吧。。。

**Comment by sabersensen** [comment]
本人觉得看了cell 还耦合model 瞬间没欲望了

**Comment by leung-c** [comment]
看一眼cell就知道了，这根本不是MVVM模式

**Comment by lizelu** [comment]
找时间改一下，之前写的Demo，一直没怎么改过~

**Comment by lizelu** [comment]
@leung-c 
已更新欢迎批评指正~
